import { Product } from '../model/product';

export const PRODUCTS: Product[] = [
  {
    product: 'Cherry',
    productGE: 'ალუბალი',
    calorie: 50,
    protein: 1,
    carbs: 12.2,
    fat: 0.3,
  },
  {
    product: 'Cherries, canned',
    productGE: 'ალუბალი, დაკონსერვებული',
    calorie: 75,
    protein: 0.7,
    carbs: 19.3,
    fat: 0.1,
  },
  {
    product: 'Cherry, sweet',
    productGE: 'ალუბალი, ტკბილი',
    calorie: 63,
    protein: 1.1,
    carbs: 16,
    fat: 0.2,
  },
  {
    product: 'American nuts',
    productGE: 'ამერიკული თხილი',
    calorie: 691,
    protein: 9.2,
    carbs: 13.9,
    fat: 72,
  },
  {
    product: 'Pineapple',
    productGE: 'ანანასი',
    calorie: 50,
    protein: 0.5,
    carbs: 13.1,
    fat: 0.1,
  },
  {
    product: 'Pineapple, canned',
    productGE: 'ანანასი, კონსერვი',
    calorie: 60,
    protein: 0.5,
    carbs: 15.6,
    fat: 0.1,
  },
  {
    product: 'Pineapple juice',
    productGE: 'ანანასის წვენი',
    calorie: 53,
    protein: 0.4,
    carbs: 12.9,
    fat: 0.1,
  },
  {
    product: 'Peanuts, roasted',
    productGE: 'არაქისი, შემწვარი',
    calorie: 585,
    protein: 23.7,
    carbs: 21.5,
    fat: 49.7,
  },
  {
    product: 'Peanut butter (> 90%)',
    productGE: 'არაქისის კარაქი (> 90%)',
    calorie: 588,
    protein: 25.1,
    carbs: 19.6,
    fat: 50.4,
  },
  {
    product: 'Peach',
    productGE: 'ატამი',
    calorie: 44,
    protein: 1.1,
    carbs: 10.6,
    fat: 0.3,
  },
  {
    product: 'Peach',
    productGE: 'ატამი',
    calorie: 39,
    protein: 0.9,
    carbs: 9.5,
    fat: 0.3,
  },
  {
    product: 'Peach, dried',
    productGE: 'ატამი, გამხმარი',
    calorie: 239,
    protein: 3.6,
    carbs: 61.3,
    fat: 0.8,
  },
  {
    product: 'Eggplant',
    productGE: 'ბადრიჯანი',
    calorie: 24,
    protein: 1,
    carbs: 5.7,
    fat: 0.2,
  },
  {
    product: 'Eggplant',
    productGE: 'ბადრიჯანი',
    calorie: 24,
    protein: 1,
    carbs: 5.7,
    fat: 0.2,
  },
  {
    product: 'Banana',
    productGE: 'ბანანი',
    calorie: 89,
    protein: 1.1,
    carbs: 22.8,
    fat: 0.3,
  },
  {
    product: 'Peas',
    productGE: 'ბარდა',
    calorie: 341,
    protein: 24.6,
    carbs: 60.4,
    fat: 1.2,
  },
  {
    product: 'Goose, liver, raw',
    productGE: 'ბატი, ღვიძლი, უმი',
    calorie: 133,
    protein: 16.4,
    carbs: 6.3,
    fat: 4.3,
  },
  {
    product: 'Goose, meat without skin',
    productGE: 'ბატი, ხორცი კანის გარეშე',
    calorie: 161,
    protein: 22.8,
    carbs: null,
    fat: 7.1,
  },
  {
    product: 'Popcorn, fat-free',
    productGE: 'ბატიბუტი, უცხიმო',
    calorie: 387,
    protein: 12.9,
    carbs: 77.9,
    fat: 4.5,
  },
  {
    product: 'Popcorn, fat',
    productGE: 'ბატიბუტი, ცხიმიანი',
    calorie: 583,
    protein: 7.3,
    carbs: 45.1,
    fat: 43.6,
  },
  {
    product: 'Frog legs',
    productGE: 'ბაყაყის ფეხები',
    calorie: 73,
    protein: 16.4,
    carbs: null,
    fat: 0.3,
  },
  {
    product: 'Pancakes',
    productGE: 'ბლინები',
    calorie: 194,
    protein: 5.2,
    carbs: 36.7,
    fat: 2.5,
  },
  {
    product: 'Radish',
    productGE: 'ბოლოკი',
    calorie: 16,
    protein: 0.7,
    carbs: 3.4,
    fat: 0.1,
  },
  {
    product: 'Brownie, cake',
    productGE: 'ბრაუნი, ნამცხვარი',
    calorie: 405,
    protein: 4.8,
    carbs: 63.9,
    fat: 16.3,
  },
  {
    product: 'Rice, white',
    productGE: 'ბრინჯი, თეთრი',
    calorie: 365,
    protein: 7.1,
    carbs: 80,
    fat: 0.7,
  },
  {
    product: 'Rice, white, medium gr ain',
    productGE: 'ბრინჯი, თეთრი, საშუალო გრ ain',
    calorie: 360,
    protein: 6.6,
    carbs: 79.3,
    fat: 0.6,
  },
  {
    product: 'Rice, brown',
    productGE: 'ბრინჯი, ყავისფერი',
    calorie: 370,
    protein: 7.9,
    carbs: 77.2,
    fat: 2.9,
  },
  {
    product: 'Brussels sprouts',
    productGE: 'ბრიუსელის კომბოსტო',
    calorie: 43,
    protein: 3.4,
    carbs: 9,
    fat: 0.3,
  },
  {
    product: 'Broccoli',
    productGE: 'ბროკოლი',
    calorie: 34,
    protein: 2.8,
    carbs: 6.6,
    fat: 0.4,
  },
  {
    product: 'Apricot',
    productGE: 'გარგარი',
    calorie: 48,
    protein: 1.4,
    carbs: 11.1,
    fat: 0.4,
  },
  {
    product: 'Apricot, dried',
    productGE: 'გარგარი, ხმელი',
    calorie: 241,
    protein: 3.4,
    carbs: 62.6,
    fat: 0.5,
  },
  {
    product: 'Pumpkin',
    productGE: 'გოგრა',
    calorie: 26,
    protein: 1,
    carbs: 6.5,
    fat: 0.1,
  },
  {
    product: 'Grapefruit',
    productGE: 'გრეიფრუტი',
    calorie: 32,
    protein: 0.6,
    carbs: 8.1,
    fat: 0.1,
  },
  {
    product: 'Grapefruit juice',
    productGE: 'გრეიფრუტის წვენი',
    calorie: 38,
    protein: 0.5,
    carbs: 9,
    fat: 0.1,
  },
  {
    product: 'Chicory (witlof)',
    productGE: 'ვარდკაჭაჭა (witlof)',
    calorie: 17,
    protein: 0.9,
    carbs: 4,
    fat: 0.1,
  },
  {
    product: 'Waffle, vanilla',
    productGE: 'ვაფლი, ვანილი',
    calorie: 441,
    protein: 5,
    carbs: 73.6,
    fat: 15.2,
  },
  {
    product: 'Waffle, chocolate',
    productGE: 'ვაფლი, შოკოლადი',
    calorie: 433,
    protein: 6.6,
    carbs: 72.4,
    fat: 14.2,
  },
  {
    product: 'Apple',
    productGE: 'ვაშლი',
    calorie: 52,
    protein: 0.3,
    carbs: 13.8,
    fat: 0.2,
  },
  {
    product: 'Apple juice',
    productGE: 'ვაშლის წვენი',
    calorie: 46,
    protein: 0.1,
    carbs: 11.3,
    fat: 0.1,
  },
  {
    product: 'Cod',
    productGE: 'ვირთევზა',
    calorie: 82,
    protein: 17.8,
    carbs: null,
    fat: 0.7,
  },
  {
    product: 'Olive',
    productGE: 'ზეთისხილი',
    calorie: 115,
    protein: 0.8,
    carbs: 6.3,
    fat: 10.7,
  },
  {
    product: 'Olive oil',
    productGE: 'ზეითუნის ზეთი',
    calorie: 884,
    protein: null,
    carbs: null,
    fat: 100,
  },
  {
    product: 'Turnip',
    productGE: 'თალგამი',
    calorie: 28,
    protein: 0.9,
    carbs: 6.4,
    fat: 0.1,
  },
  {
    product: 'Honey',
    productGE: 'თაფლი',
    calorie: 304,
    protein: 0.3,
    carbs: 82.4,
    fat: null,
  },
  {
    product: 'Fish oil, salmon',
    productGE: 'თევზის ზეთი, ორაგული',
    calorie: 902,
    protein: null,
    carbs: null,
    fat: 100,
  },
  {
    product: 'Tuna',
    productGE: 'თინუსი',
    calorie: 144,
    protein: 23.3,
    carbs: null,
    fat: 4.9,
  },
  {
    product: 'Tuna, canned in water',
    productGE: 'თინუსი, დაკონსერვებული წყალში',
    calorie: 128,
    protein: 23.6,
    carbs: null,
    fat: 3,
  },
  {
    product: 'Nut',
    productGE: 'თხილი',
    calorie: 628,
    protein: 15,
    carbs: 16.7,
    fat: 60.8,
  },
  {
    product: 'Yam (sweet potato)',
    productGE: 'იამი (ტკბილი კარტოფილი)',
    calorie: 118,
    protein: 1.5,
    carbs: 27.9,
    fat: 0.2,
  },
  {
    product: 'Turkey, Barkley meat',
    productGE: 'ინდაური, ბარკლის ხორცი',
    calorie: 108,
    protein: 20.4,
    carbs: null,
    fat: 2.4,
  },
  {
    product: 'Turkey, breast meat',
    productGE: 'ინდაური, მკერდის ხორცი',
    calorie: 111,
    protein: 24.6,
    carbs: null,
    fat: 0.7,
  },
  {
    product: 'Turkey, liver, raw',
    productGE: 'ინდაური, ღვიძლი, ნედლი',
    calorie: 228,
    protein: 17.8,
    carbs: 2.3,
    fat: 16.4,
  },
  {
    product: 'Turkey ham, sliced',
    productGE: 'ინდაურის ლორი, დაჭრილი',
    calorie: 124,
    protein: 19.6,
    carbs: 2.9,
    fat: 3.8,
  },
  {
    product: 'Yogurt, non-fat',
    productGE: 'იოგურტი, უცხიმო',
    calorie: 56,
    protein: 5.7,
    carbs: 7.7,
    fat: 0.2,
  },
  {
    product: 'Yogurt, fat',
    productGE: 'იოგურტი, ცხიმიანი',
    calorie: 61,
    protein: 3.5,
    carbs: 4.7,
    fat: 3.3,
  },
  {
    product: 'Venison, lean',
    productGE: 'ირმის ხორცი, მჭლე',
    calorie: 120,
    protein: 23,
    carbs: null,
    fat: 2.4,
  },
  {
    product: 'Spinach',
    productGE: 'ისპანახი',
    calorie: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
  },
  {
    product: 'Duck, liver',
    productGE: 'იხვი, ღვიძლი',
    calorie: 136,
    protein: 18.7,
    carbs: 3.5,
    fat: 4.6,
  },
  {
    product: 'Duck, meat without skin',
    productGE: 'იხვი, ხორცი კანის გარეშე',
    calorie: 135,
    protein: 18.3,
    carbs: 0.9,
    fat: 6,
  },
  {
    product: 'Walnut',
    productGE: 'კაკალი',
    calorie: 654,
    protein: 15.2,
    carbs: 13.7,
    fat: 65.2,
  },
  {
    product: 'Cocoa powder',
    productGE: 'კაკაოს ფხვნილი',
    calorie: 228,
    protein: 19.6,
    carbs: 57.9,
    fat: 13.7,
  },
  {
    product: 'Trout',
    productGE: 'კალმახი',
    calorie: 148,
    protein: 20.8,
    carbs: null,
    fat: 6.6,
  },
  {
    product: 'Of flounder',
    productGE: 'კამბალისნაერთა',
    calorie: 91,
    protein: 18.8,
    carbs: null,
    fat: 1.2,
  },
  {
    product: 'Potatoes',
    productGE: 'კარტოფილი',
    calorie: 77,
    protein: 2,
    carbs: 17.5,
    fat: 0.1,
  },
  {
    product: 'French fries',
    productGE: 'კარტოფილი ფრი',
    calorie: 331,
    protein: 3.5,
    carbs: 40.1,
    fat: 17.4,
  },
  {
    product: 'Potatoes, white',
    productGE: 'კარტოფილი, თეთრი',
    calorie: 69,
    protein: 1.7,
    carbs: 15.7,
    fat: 0.1,
  },
  {
    product: 'Potatoes, red',
    productGE: 'კარტოფილი, წითელი',
    calorie: 70,
    protein: 1.9,
    carbs: 15.9,
    fat: 0.1,
  },
  {
    product: 'Potato chips',
    productGE: 'კარტოფილის ჩიფსები',
    calorie: 542,
    protein: 6.6,
    carbs: 50.8,
    fat: 36.4,
  },
  {
    product: 'Cashew',
    productGE: 'კეშიუ',
    calorie: 553,
    protein: 18.2,
    carbs: 30.2,
    fat: 43.9,
  },
  {
    product: 'Egg',
    productGE: 'კვერცხი',
    calorie: 143,
    protein: 12.6,
    carbs: 0.8,
    fat: 9.9,
  },
  {
    product: 'Egg yolk',
    productGE: 'კვერცხის გული',
    calorie: 317,
    protein: 15.9,
    carbs: 3.6,
    fat: 26.5,
  },
  {
    product: 'Egg white',
    productGE: 'კვერცხის ცილა',
    calorie: 48,
    protein: 10.9,
    carbs: 0.7,
    fat: 0.2,
  },
  {
    product: 'Kiwi',
    productGE: 'კივი',
    calorie: 61,
    protein: 1.1,
    carbs: 14.7,
    fat: 0.5,
  },
  {
    product: 'Cucumber',
    productGE: 'კიტრი',
    calorie: 12,
    protein: 0.6,
    carbs: 2.2,
    fat: 0.2,
  },
  {
    product: 'Cabbage',
    productGE: 'კომბოსტო',
    calorie: 25,
    protein: 1.3,
    carbs: 5.8,
    fat: 0.1,
  },
  {
    product: 'Cabbage, Savoy',
    productGE: 'კომბოსტო, სავოიის',
    calorie: 27,
    protein: 2,
    carbs: 6.1,
    fat: 0.1,
  },
  {
    product: 'Cabbage, red',
    productGE: 'კომბოსტო, წითელი',
    calorie: 31,
    protein: 1.4,
    carbs: 7.4,
    fat: 0.2,
  },
  {
    product: 'Crab',
    productGE: 'კრაბი',
    calorie: 87,
    protein: 18.1,
    carbs: null,
    fat: 1.1,
  },
  {
    product: 'Crab, canned',
    productGE: 'კრაბი, კონსერვი',
    calorie: 99,
    protein: 20.5,
    carbs: null,
    fat: 1.2,
  },
  {
    product: 'Croissant',
    productGE: 'კრუასანი',
    calorie: 406,
    protein: 8.2,
    carbs: 45.8,
    fat: 21,
  },
  {
    product: 'Couscous',
    productGE: 'კუსკუსი',
    calorie: 376,
    protein: 12.8,
    carbs: 77.4,
    fat: 0.6,
  },
  {
    product: 'Lactose',
    productGE: 'ლაქტოზა',
    calorie: 400,
    protein: null,
    carbs: 100,
    fat: null,
  },
  {
    product: 'Figs, dried',
    productGE: 'ლეღვი, გამხმარი',
    calorie: 249,
    protein: 3.3,
    carbs: 63.9,
    fat: 0.9,
  },
  {
    product: 'Lemon juice',
    productGE: 'ლიმონის წვენი',
    calorie: 21,
    protein: 0.4,
    carbs: 6.5,
    fat: 0.3,
  },
  {
    product: 'Beans, fresh, green',
    productGE: 'ლობიო, ახალი, მწვანე',
    calorie: 31,
    protein: 1.8,
    carbs: 7,
    fat: 0.2,
  },
  {
    product: 'Beans, pink',
    productGE: 'ლობიო, ვარდისფერი',
    calorie: 343,
    protein: 21,
    carbs: 64.2,
    fat: 1.1,
  },
  {
    product: 'Beans, white',
    productGE: 'ლობიო, თეთრი',
    calorie: 333,
    protein: 23.4,
    carbs: 60.3,
    fat: 0.9,
  },
  {
    product: 'Beans, speckled',
    productGE: 'ლობიო, ლაქებიანი',
    calorie: 347,
    protein: 21.4,
    carbs: 62.6,
    fat: 1.2,
  },
  {
    product: 'Beans, small white',
    productGE: 'ლობიო, პატარა თეთრი',
    calorie: 336,
    protein: 21.1,
    carbs: 62.3,
    fat: 1.2,
  },
  {
    product: 'Beans, yellow',
    productGE: 'ლობიო, ყვითელი',
    calorie: 345,
    protein: 22,
    carbs: 60.7,
    fat: 2.6,
  },
  {
    product: 'Beans, black',
    productGE: 'ლობიო, შავი',
    calorie: 341,
    protein: 21.6,
    carbs: 62.4,
    fat: 1.4,
  },
  {
    product: 'Beans, red',
    productGE: 'ლობიო, წითელი',
    calorie: 333,
    protein: 23.6,
    carbs: 60,
    fat: 0.8,
  },
  {
    product: 'Lobster',
    productGE: 'ლობსტერი',
    calorie: 90,
    protein: 18.8,
    carbs: 0.5,
    fat: 0.9,
  },
  {
    product: 'Ham (pork), sliced',
    productGE: 'ლორი (ღორის), დაჭრილი',
    calorie: 116,
    protein: 21,
    carbs: 1,
    fat: 3.2,
  },
  {
    product: 'Pasta, dry',
    productGE: 'მაკარონი, მშრალი',
    calorie: 371,
    protein: 13,
    carbs: 74.7,
    fat: 1.5,
  },
  {
    product: 'Pasta, dry',
    productGE: 'მაკარონი, მშრალი',
    calorie: 371,
    protein: 13,
    carbs: 74.7,
    fat: 1.5,
  },
  {
    product: 'Strawberry',
    productGE: 'მარწყვი',
    calorie: 32,
    protein: 0.7,
    carbs: 7.7,
    fat: 0.3,
  },
  {
    product: 'Cuttlefish',
    productGE: 'მელანთევზი',
    calorie: 79,
    protein: 16.2,
    carbs: 0.8,
    fat: 0.7,
  },
  {
    product: 'sunflower oil',
    productGE: 'მზესუმზირის ზეთი',
    calorie: 884,
    protein: null,
    carbs: null,
    fat: 100,
  },
  {
    product: 'Mussels',
    productGE: 'მიდიები',
    calorie: 86,
    protein: 11.9,
    carbs: 3.7,
    fat: 2.2,
  },
  {
    product: 'Mussels',
    productGE: 'მიდიები',
    calorie: 106,
    protein: 20.3,
    carbs: 0.9,
    fat: 1.7,
  },
  {
    product: 'Muesli',
    productGE: 'მუსლი',
    calorie: 340,
    protein: 9.7,
    carbs: 77.8,
    fat: 4.9,
  },
  {
    product: 'Blueberry',
    productGE: 'მოცვი',
    calorie: 57,
    protein: 0.7,
    carbs: 14.5,
    fat: 0.3,
  },
  {
    product: 'Pear',
    productGE: 'მსხალი',
    calorie: 58,
    protein: 0.4,
    carbs: 15.5,
    fat: 0.1,
  },
  {
    product: 'Chickpea',
    productGE: 'მუხუდო',
    calorie: 364,
    protein: 19.3,
    carbs: 60.7,
    fat: 6,
  },
  {
    product: 'Pickled cucumber',
    productGE: 'მწნილი კიტრის',
    calorie: 11,
    protein: 0.3,
    carbs: 2.3,
    fat: 0.2,
  },
  {
    product: 'Nacho with cheese',
    productGE: 'ნაჩოს ყველით',
    calorie: 306,
    protein: 8.1,
    carbs: 32.2,
    fat: 16.8,
  },
  {
    product: 'Nacho chips',
    productGE: 'ნაჩოს ჩიპი',
    calorie: 514,
    protein: 8.2,
    carbs: 61.7,
    fat: 26.1,
  },
  {
    product: 'Melon, watermelon',
    productGE: 'ნესვი, საზამთრო',
    calorie: 34,
    protein: 0.8,
    carbs: 8.2,
    fat: 0.2,
  },
  {
    product: 'Garlic',
    productGE: 'ნიორი',
    calorie: 149,
    protein: 6.4,
    carbs: 33.1,
    fat: 0.5,
  },
  {
    product: 'Almonds',
    productGE: 'ნუში',
    calorie: 575,
    protein: 21.2,
    carbs: 21.7,
    fat: 49.4,
  },
  {
    product: 'Okra',
    productGE: 'ოკრა',
    calorie: 31,
    protein: 2,
    carbs: 7,
    fat: 0.1,
  },
  {
    product: 'Salmon',
    productGE: 'ორაგული',
    calorie: 142,
    protein: 19.8,
    carbs: null,
    fat: 6.3,
  },
  {
    product: 'Lentils',
    productGE: 'ოსპი',
    calorie: 353,
    protein: 25.8,
    carbs: 60.1,
    fat: 1.1,
  },
  {
    product: 'Papaya',
    productGE: 'პაპაია',
    calorie: 39,
    protein: 0.6,
    carbs: 9.8,
    fat: 0.1,
  },
  {
    product: 'Tomato',
    productGE: 'პომიდორი',
    calorie: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
  },
  {
    product: 'Tomato, pink',
    productGE: 'პომიდორი, ვარდისფერი',
    calorie: 16,
    protein: 1.2,
    carbs: 3.2,
    fat: 0.2,
  },
  {
    product: 'Tomatoes, canned',
    productGE: 'პომიდორი, კონსერვი',
    calorie: 17,
    protein: 0.8,
    carbs: 4,
    fat: 0.1,
  },
  {
    product: 'Tomato, yellow',
    productGE: 'პომიდორი, ყვითელი',
    calorie: 15,
    protein: 1,
    carbs: 3,
    fat: 0.3,
  },
  {
    product: 'Bread, white',
    productGE: 'პური, თეთრი',
    calorie: 266,
    protein: 7.6,
    carbs: 50.6,
    fat: 3.3,
  },
  {
    product: 'Bread, raisins',
    productGE: 'პური, ქიშმიში',
    calorie: 274,
    protein: 7.9,
    carbs: 52.3,
    fat: 4.4,
  },
  {
    product: 'Bread, mixed grain',
    productGE: 'პური, შერეული მარცვლეული',
    calorie: 265,
    protein: 13.4,
    carbs: 43.3,
    fat: 4.2,
  },
  {
    product: 'Bread, oats',
    productGE: 'პური, შვრიის',
    calorie: 269,
    protein: 8.4,
    carbs: 48.5,
    fat: 4.4,
  },
  {
    product: 'Bread, rye',
    productGE: 'პური, ჭვავის',
    calorie: 258,
    protein: 8.5,
    carbs: 48.3,
    fat: 3.3,
  },
  {
    product: 'Bread, wheat',
    productGE: 'პური, ხორბლის',
    calorie: 266,
    protein: 10.9,
    carbs: 47.5,
    fat: 3.6,
  },
  {
    product: 'Raspberry',
    productGE: 'ჟოლო',
    calorie: 52,
    protein: 1.2,
    carbs: 11.9,
    fat: 0.7,
  },
  {
    product: 'Milk, 1% fat',
    productGE: 'რძე, 1% ცხიმი',
    calorie: 42,
    protein: 3.4,
    carbs: 5,
    fat: 1,
  },
  {
    product: 'Milk, 1.5% fat',
    productGE: 'რძე, 1,5% ცხიმი',
    calorie: 46,
    protein: 3.3,
    carbs: 4.9,
    fat: 1.5,
  },
  {
    product: 'Milk, 2% fat',
    productGE: 'რძე, 2% ცხიმი',
    calorie: 50,
    protein: 3.3,
    carbs: 4.8,
    fat: 2,
  },
  {
    product: 'Milk, 3.25% fat',
    productGE: 'რძე, 3.25% ცხიმი',
    calorie: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
  },
  {
    product: 'Milk, skimmed',
    productGE: 'რძე, უცხიმო',
    calorie: 34,
    protein: 3.4,
    carbs: 5,
    fat: 0.1,
  },
  {
    product: 'Milk powder, non-fat, dry',
    productGE: 'რძის ფხვნილი, არასამთავრობო ცხიმი, მშრალი',
    calorie: 362,
    protein: 36.2,
    carbs: 52,
    fat: 0.8,
  },
  {
    product: 'Watermelon',
    productGE: 'საზამთრო',
    calorie: 30,
    protein: 0.6,
    carbs: 7.6,
    fat: 0.2,
  },
  {
    product: 'Lettuce, green',
    productGE: 'სალათის ფოთოლი, მწვანე',
    calorie: 15,
    protein: 1.4,
    carbs: 2.8,
    fat: 0.2,
  },
  {
    product: 'Lettuce, red',
    productGE: 'სალათის ფოთოლი, წითელი',
    calorie: 16,
    protein: 1.3,
    carbs: 2.3,
    fat: 0.2,
  },
  {
    product: 'Terrible',
    productGE: 'სატაცური',
    calorie: 20,
    protein: 2.2,
    carbs: 3.9,
    fat: 0.1,
  },
  {
    product: 'Flax',
    productGE: 'სელი',
    calorie: 534,
    protein: 18.3,
    carbs: 28.9,
    fat: 42.2,
  },
  {
    product: 'Flax oil',
    productGE: 'სელის ზეთი',
    calorie: 884,
    protein: null,
    carbs: null,
    fat: 100,
  },
  {
    product: 'Corn, raw',
    productGE: 'სიმინდი, ნედლი',
    calorie: 86,
    protein: 3.3,
    carbs: 18.7,
    fat: 1.4,
  },
  {
    product: 'Corn, dry',
    productGE: 'სიმინდი, ხმელი',
    calorie: 365,
    protein: 9.4,
    carbs: 74.3,
    fat: 4.7,
  },
  {
    product: 'Corn oil',
    productGE: 'სიმინდის ზეთი',
    calorie: 884,
    protein: null,
    carbs: null,
    fat: 100,
  },
  {
    product: 'Ostrich meat',
    productGE: 'სირაქლემას, ხორცი',
    calorie: 115,
    protein: 22.9,
    carbs: null,
    fat: 2,
  },
  {
    product: 'Mackerel',
    productGE: 'სკუმბრია',
    calorie: 205,
    protein: 18.6,
    carbs: null,
    fat: 13.9,
  },
  {
    product: 'Soy',
    productGE: 'სოიო',
    calorie: 446,
    protein: 36.5,
    carbs: 30.2,
    fat: 19.9,
  },
  {
    product: 'Soy, green',
    productGE: 'სოიო, მწვანე',
    calorie: 147,
    protein: 13,
    carbs: 11.1,
    fat: 6.8,
  },
  {
    product: 'Soybean oil',
    productGE: 'სოიოს ზეთი',
    calorie: 884,
    protein: null,
    carbs: null,
    fat: 100,
  },
  {
    product: 'Mushroom, white',
    productGE: 'სოკო, თეთრი',
    calorie: 22,
    protein: 3.1,
    carbs: 3.3,
    fat: 0.3,
  },
  {
    product: 'Spaghetti, spinach, dry',
    productGE: 'სპაგეტი, ისპანახი, მშრალი',
    calorie: 372,
    protein: 13.4,
    carbs: 74.8,
    fat: 1.6,
  },
  {
    product: 'Spaghetti, dry',
    productGE: 'სპაგეტი, მშრალი',
    calorie: 371,
    protein: 13,
    carbs: 74.7,
    fat: 1.5,
  },
  {
    product: 'Spaghetti, dry',
    productGE: 'სპაგეტი, მშრალი',
    calorie: 371,
    protein: 13,
    carbs: 74.7,
    fat: 1.5,
  },
  {
    product: 'Carrot',
    productGE: 'სტაფილო',
    calorie: 41,
    protein: 0.9,
    carbs: 9.6,
    fat: 0.2,
  },
  {
    product: 'Carrot juice',
    productGE: 'სტაფილოს წვენი',
    calorie: 40,
    protein: 1,
    carbs: 9.3,
    fat: 0.2,
  },
  {
    product: 'Sweet potatoes',
    productGE: 'ტკბილი კარტოფილი',
    calorie: 86,
    protein: 1.6,
    carbs: 20.1,
    fat: 0.1,
  },
  {
    product: 'Millet',
    productGE: 'ფეტვი',
    calorie: 378,
    protein: 11,
    carbs: 72.9,
    fat: 4.2,
  },
  {
    product: 'Orange',
    productGE: 'ფორთოხალი',
    calorie: 47,
    protein: 0.9,
    carbs: 11.8,
    fat: 0.1,
  },
  {
    product: 'Orange juice',
    productGE: 'ფორთოხლის წვენი',
    calorie: 47,
    protein: 0.7,
    carbs: 11,
    fat: 0.2,
  },
  {
    product: 'Fructose',
    productGE: 'ფრუქტოზა',
    calorie: 400,
    protein: null,
    carbs: 100,
    fat: null,
  },
  {
    product: 'Pistachio',
    productGE: 'ფსტა',
    calorie: 562,
    protein: 20.3,
    carbs: 27.5,
    fat: 45.4,
  },
  {
    product: 'Pistachio, fried, salt',
    productGE: 'ფსტა, შემწვარი, მარილი',
    calorie: 568,
    protein: 21.4,
    carbs: 26.8,
    fat: 46,
  },
  {
    product: 'Chicken, breast meat',
    productGE: 'ქათამი, მკერდის ხორცი',
    calorie: 114,
    protein: 21.2,
    carbs: null,
    fat: 2.6,
  },
  {
    product: 'Chicken, breast, sliced',
    productGE: 'ქათამი, მკერდის, დაჭრილი',
    calorie: 79,
    protein: 16.8,
    carbs: 2.2,
    fat: 0.4,
  },
  {
    product: 'Chicken, leg meat',
    productGE: 'ქათამი, ფეხის ხორცი',
    calorie: 120,
    protein: 20.1,
    carbs: null,
    fat: 3.8,
  },
  {
    product: 'Chicken, liver',
    productGE: 'ქათამი, ღვიძლის',
    calorie: 119,
    protein: 16.9,
    carbs: 0.7,
    fat: 4.8,
  },
  {
    product: 'Herring',
    productGE: 'ქაშაყი',
    calorie: 158,
    protein: 18,
    carbs: null,
    fat: 9,
  },
  {
    product: 'Barley',
    productGE: 'ქერი',
    calorie: 352,
    protein: 9.9,
    carbs: 77.7,
    fat: 1.2,
  },
  {
    product: 'Raisins, dried',
    productGE: 'ქიშმიში, გამხმარი',
    calorie: 299,
    protein: 3.1,
    carbs: 79.2,
    fat: 0.5,
  },
  {
    product: 'Plum',
    productGE: 'ქლიავი',
    calorie: 46,
    protein: 0.7,
    carbs: 11.4,
    fat: 0.3,
  },
  {
    product: 'Plums, dried',
    productGE: 'ქლიავი, გამხმარი',
    calorie: 240,
    protein: 2.2,
    carbs: 63.9,
    fat: 0.4,
  },
  {
    product: 'coconut',
    productGE: 'ქოქოსი',
    calorie: 354,
    protein: 3.3,
    carbs: 15.2,
    fat: 33.5,
  },
  {
    product: 'Liver pate',
    productGE: 'ღვიძლის პაშტეტი',
    calorie: 319,
    protein: 14.2,
    carbs: 1.5,
    fat: 28,
  },
  {
    product: 'Liver sausage',
    productGE: 'ღვიძლის ძეხვი',
    calorie: 326,
    protein: 14.1,
    carbs: 2.2,
    fat: 28.5,
  },
  {
    product: 'Pork, bacon',
    productGE: 'ღორის ხორცი, ბეკონი',
    calorie: 458,
    protein: 11.6,
    carbs: 0.7,
    fat: 45,
  },
  {
    product: 'Pork, lean',
    productGE: 'ღორის ხორცი, მჭლე',
    calorie: 120,
    protein: 20.7,
    carbs: null,
    fat: 3.5,
  },
  {
    product: 'Pork leg (ham), lean',
    productGE: 'ღორის, ფეხი (ლორი), მჭლე',
    calorie: 136,
    protein: 20.5,
    carbs: null,
    fat: 5.4,
  },
  {
    product: 'Cauliflower',
    productGE: 'ყვავილოვანი კომბოსტო',
    calorie: 25,
    protein: 1.9,
    carbs: 5,
    fat: 0.3,
  },
  {
    product: 'Mozzarella cheese, low fat',
    productGE: 'ყველი მოცარელა, დაბალი ცხიმიანობა',
    calorie: 254,
    protein: 24.3,
    carbs: 2.8,
    fat: 15.9,
  },
  {
    product: 'Mozzarella cheese, fatty',
    productGE: 'ყველი მოცარელა, ცხიმიანი',
    calorie: 300,
    protein: 22.2,
    carbs: 2.2,
    fat: 22.4,
  },
  {
    product: 'Cheese, Gouda',
    productGE: 'ყველი, გუდა',
    calorie: 356,
    protein: 24.9,
    carbs: 2.2,
    fat: 27.4,
  },
  {
    product: 'Grapes',
    productGE: 'ყურძენი',
    calorie: 69,
    protein: 0.7,
    carbs: 18.1,
    fat: 0.2,
  },
  {
    product: 'Grape juice',
    productGE: 'ყურძნის წვენი',
    calorie: 60,
    protein: 0.4,
    carbs: 14.8,
    fat: 0.1,
  },
  {
    product: 'Shallot',
    productGE: 'შალოტი',
    calorie: 72,
    protein: 2.5,
    carbs: 16.8,
    fat: 0.1,
  },
  {
    product: 'Sugar, sucrose',
    productGE: 'შაქარი, საქაროზა',
    calorie: 387,
    protein: null,
    carbs: 100,
    fat: null,
  },
  {
    product: 'Sugar, brown',
    productGE: 'შაქარი, ყავისფერი',
    calorie: 380,
    protein: 0.1,
    carbs: 98.1,
    fat: null,
  },
  {
    product: 'Powdered sugar',
    productGE: 'შაქრის ფხვნილი',
    calorie: 389,
    protein: null,
    carbs: 99.8,
    fat: null,
  },
  {
    product: 'Oats',
    productGE: 'შვრია',
    calorie: 389,
    protein: 16.9,
    carbs: 66.3,
    fat: 6.9,
  },
  {
    product: 'Oats, powder',
    productGE: 'შვრია, ფხვნილი',
    calorie: 388,
    protein: 8.5,
    carbs: 70.7,
    fat: 7.9,
  },
  {
    product: 'Chocolate, white',
    productGE: 'შოკოლადი, თეთრი',
    calorie: 539,
    protein: 5.9,
    carbs: 59.2,
    fat: 32.1,
  },
  {
    product: 'Chocolate, dark, 45-59% cocoa',
    productGE: 'შოკოლადი, მუქი, 45-59% კაკაო',
    calorie: 546,
    protein: 4.9,
    carbs: 61.2,
    fat: 31.3,
  },
  {
    product: 'Chocolate, dark, 60-69% cocoa',
    productGE: 'შოკოლადი, მუქი, 60-69% კაკაო',
    calorie: 579,
    protein: 6.1,
    carbs: 52.4,
    fat: 38.3,
  },
  {
    product: 'Chocolate, dark, 70-85% cocoa',
    productGE: 'შოკოლადი, მუქი, 70-85% კაკაო',
    calorie: 598,
    protein: 7.8,
    carbs: 45.9,
    fat: 42.6,
  },
  {
    product: 'Chocolate milk',
    productGE: 'შოკოლადის რძე',
    calorie: 535,
    protein: 7.7,
    carbs: 59.4,
    fat: 29.7,
  },
  {
    product: 'Serum concentrate',
    productGE: 'შრატის კონცენტრატი',
    calorie: 407,
    protein: 80,
    carbs: 6,
    fat: 7,
  },
  {
    product: 'Serum isolate',
    productGE: 'შრატის, ისოლატი',
    calorie: 368,
    protein: 89,
    carbs: 0.7,
    fat: 1,
  },
  {
    product: 'Sheep, lean',
    productGE: 'ცხვარი, მჭლე',
    calorie: 143,
    protein: 20.9,
    carbs: null,
    fat: 5.9,
  },
  {
    product: 'Chestnut',
    productGE: 'წაბლი',
    calorie: 196,
    protein: 1.6,
    carbs: 44.2,
    fat: 1.3,
  },
  {
    product: 'Pepper, green, sweet',
    productGE: 'წიწაკა, მწვანე, ტკბილი',
    calorie: 20,
    protein: 0.9,
    carbs: 4.6,
    fat: 0.2,
  },
  {
    product: 'Pepper, yellow, sweet',
    productGE: 'წიწაკა, ყვითელი, ტკბილი',
    calorie: 27,
    protein: 1,
    carbs: 6.3,
    fat: 0.2,
  },
  {
    product: 'Pepper, red, sweet',
    productGE: 'წიწაკა, წითელი, ტკბილი',
    calorie: 31,
    protein: 1,
    carbs: 6,
    fat: 0.3,
  },
  {
    product: 'Buckwheat',
    productGE: 'წიწიბურა',
    calorie: 343,
    protein: 13.3,
    carbs: 71.5,
    fat: 3.4,
  },
  {
    product: 'Buckwheat flour',
    productGE: 'წიწიბურა ფქვილი',
    calorie: 335,
    protein: 12.6,
    carbs: 70.6,
    fat: 3.1,
  },
  {
    product: 'Water',
    productGE: 'წყალი',
    calorie: null,
    protein: null,
    carbs: null,
    fat: null,
  },
  {
    product: 'Beetroot',
    productGE: 'ჭარხალი',
    calorie: 43,
    protein: 1.6,
    carbs: 9.6,
    fat: 0.2,
  },
  {
    product: 'Rye',
    productGE: 'ჭვავი',
    calorie: 338,
    protein: 10.3,
    carbs: 75.9,
    fat: 1.6,
  },
  {
    product: 'Cottage cheese, 1% fat',
    productGE: 'ხაჭო, 1% ცხიმი',
    calorie: 72,
    protein: 12.4,
    carbs: 2.7,
    fat: 1,
  },
  {
    product: 'Cottage cheese, 2% fat',
    productGE: 'ხაჭო, 2% ცხიმი',
    calorie: 86,
    protein: 11.8,
    carbs: 3.7,
    fat: 2.5,
  },
  {
    product: 'Cottage cheese, non-fat',
    productGE: 'ხაჭო, არასამთავრობო ცხიმი',
    calorie: 72,
    protein: 10.3,
    carbs: 6.7,
    fat: 0.3,
  },
  {
    product: 'Onion',
    productGE: 'ხახვი',
    calorie: 40,
    protein: 1.1,
    carbs: 9.3,
    fat: 0.1,
  },
  {
    product: 'Calf, lean',
    productGE: 'ხბო, მჭლე',
    calorie: 116,
    protein: 20.2,
    carbs: null,
    fat: 3.3,
  },
  {
    product: 'wheat',
    productGE: 'ხორბალი',
    calorie: 342,
    protein: 11.3,
    carbs: 75.9,
    fat: 1.7,
  },
  {
    product: 'Wheat flour',
    productGE: 'ხორბლის ფქვილი',
    calorie: 339,
    protein: 13.7,
    carbs: 72.6,
    fat: 1.9,
  },
  {
    product: 'Meat, chopped',
    productGE: 'ხორცი, დაჭრილი',
    calorie: 176,
    protein: 28.1,
    carbs: 5.7,
    fat: 3.8,
  },
  {
    product: 'Meat, lean',
    productGE: 'ხორცი, მჭლე',
    calorie: 141,
    protein: 21.6,
    carbs: null,
    fat: 5.5,
  },
  {
    product: 'Curly cabbage',
    productGE: 'ხუჭუშა კომბოსტო',
    calorie: 50,
    protein: 3.3,
    carbs: 10,
    fat: 0.7,
  },
  {
    product: 'Hot dog',
    productGE: 'ჰოთდოგი',
    calorie: 247,
    protein: 10.6,
    carbs: 18.4,
    fat: 14.8,
  },
  {
    product: 'Churchhkela (new)',
    productGE: 'ჩურჩხელა (ახალი)',
    calorie: 200,
    protein: null,
    carbs: null,
    fat: null,
  },
  {
    product: 'Churchhkela (dry)',
    productGE: 'ჩურჩხელა (მშრალი)',
    calorie: 228,
    protein: null,
    carbs: null,
    fat: null,
  },
  {
    product: 'Pomegranate',
    productGE: 'ბროწეული',
    calorie: 82,
    protein: 1.7,
    carbs: 19,
    fat: null,
  },
  {
    product: 'coffee',
    productGE: 'ყავა',
    calorie: 0,
    protein: 0.1,
    carbs: 0,
    fat: 0,
  },
  {
    product: 'Tea',
    productGE: 'ჩაი',
    calorie: 1,
    protein: 0.1,
    carbs: 0.1,
    fat: 0,
  },
  {
    product: 'Mandarin',
    productGE: 'მანდარინი',
    calorie: 53,
    protein: 0.8,
    carbs: 13,
    fat: null,
  },
];
